[workspace]
exclude = ["vendor/rmcp", "vendor/graphql-ws-client", "vendor/cynic-introspection", "vendor/protox-parse", "vendor/rust_socketio", "vendor/rust_engineio", "vendor/rumqttc", "vendor/wsdl"]
members = ["crates/core", "crates/server", "crates/formats", "crates/script-runtime", "crates/protocols", "desktop"]
default-members = ["crates/core", "crates/server", "crates/formats", "crates/script-runtime", "crates/protocols"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.94"

[workspace.dependencies]
prost = "0.14"
prost-reflect = { version = "0.16", features = ["serde"] }
protox = "0.9"
tonic = { version = "0.14", features = ["tls-native-roots"] }
tonic-reflection = "0.14"
anyhow = "1"
axum = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4", "serde"] }
apollo-parser = "=0.8.6"
cynic-parser = { version = "=0.11.2", features = ["pretty"] }
async-graphql-parser = "=7.2.1"
cynic = "=3.14.0"
cynic-introspection = { version = "=3.14.0", path = "vendor/cynic-introspection" }
graphql-ws-client = { version = "=0.13.0", path = "vendor/graphql-ws-client", default-features = false }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json", "stream", "gzip", "brotli", "deflate"] }

[profile.release]
lto = "thin"
strip = "symbols"
codegen-units = 1

[patch.crates-io]
protox-parse = { path = "vendor/protox-parse" }

rust_socketio = { path = "vendor/rust_socketio" }
rust_engineio = { path = "vendor/rust_engineio" }

rumqttc = { path = "vendor/rumqttc" }

wsdl = { path = "vendor/wsdl" }

rmcp = { path = "vendor/rmcp" }
