import {useEffect,useRef,useState} from "react";
import {useQuery,useQueryClient} from "@tanstack/react-query";
import {Button,Callout,Card,Checkbox,Flex,Text,TextArea,TextField} from "@radix-ui/themes";
import {api} from "../../shared/api";
import {t,useLanguage} from "../../shared/i18n";
import {liveError} from "../../shared/i18n/errors";
import {Choice,Field} from "../../shared/ui";
import {useWorkbench} from "../workbench/context";
import type {NotificationTarget,NotificationDelivery,NotificationSettings} from "../../shared/types";
const fresh=()=>({id:"",revision:0,settings:{name:"",kind:"webhook",enabled:false,statuses:["failed"],changes_only:false,language:"en" as "en"|"zh-CN"},keep:false,endpoint:"",signing_secret:"",routing_key:"",host:"",port:587,tls:"starttls",from:"",to:"",username:"",password:""});
const deliveryStatus=(value:string)=>value==="sent"?t("已发送"):value==="failed"?t("发送失败"):value==="cancelled"?t("已取消"):value==="sending"?t("发送中"):t("等待发送");
export default function NotificationsPanel(){
 useLanguage();const state=useWorkbench(),client=useQueryClient(),workspace=state.draft?.id??"",scope=JSON.stringify([state.accountId,workspace]);
 const [edit,setEdit]=useState(fresh),[pending,setPending]=useState(false),[error,setError]=useState<ReturnType<typeof liveError>>("");const identity=JSON.stringify([scope,edit]);const latest=useRef(identity);latest.current=identity;const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const targets=useQuery({queryKey:["notification-targets",state.accountId,workspace],queryFn:()=>api<NotificationTarget[]>(`/api/workspaces/${workspace}/notifications`),enabled:state.authenticated&&!!workspace});
 const ledger=useQuery({queryKey:["notification-deliveries",state.accountId,workspace],queryFn:()=>api<NotificationDelivery[]>(`/api/workspaces/${workspace}/notification-deliveries`),enabled:state.authenticated&&!!workspace,refetchInterval:5000});
 const settings=edit.settings;const change=(patch:Partial<NotificationSettings>)=>setEdit({...edit,settings:{...settings,...patch}});
 function choose(channel:NotificationTarget){setEdit({...fresh(),id:channel.id,revision:channel.revision,settings:structuredClone(channel.settings),keep:true,host:channel.smtp?.host??"",port:channel.smtp?.port??587,tls:channel.smtp?.tls??"starttls",from:channel.smtp?.from??"",to:channel.smtp?.to.join("\n")??""});setError("");}
 async function action(path:string,body?:unknown,method="POST"){if(pending)return;const origin=identity;setPending(true);setError("");try{await api(`/api/workspaces/${workspace}/${path}`,method,body);if(mounted.current&&latest.current===origin){await client.invalidateQueries({queryKey:["notification-targets",state.accountId,workspace]});await client.invalidateQueries({queryKey:["notification-deliveries",state.accountId,workspace]});if(path==="notifications"||method==="PUT")setEdit(fresh());}}catch(error){if(mounted.current&&latest.current===origin)setError(liveError(error));}finally{if(mounted.current)setPending(false);}}
 function save(){let credentials:unknown;if(settings.kind==="email"){credentials={smtp:{host:edit.host,port:edit.port,tls:edit.tls,from:edit.from,to:edit.to.split("\n").map(value=>value.trim()).filter(Boolean),...(!edit.keep?{username:edit.username,password:edit.password}:{})}};}else if(!edit.keep){credentials={endpoint:edit.endpoint,signing_secret:edit.signing_secret,routing_key:edit.routing_key};}void action(edit.id?`notifications/${edit.id}`:"notifications",{settings,...(credentials?{credentials}:{}),...(edit.id?{expected_revision:edit.revision}:{})},edit.id?"PUT":"POST");}
 if(!state.draft)return null;
 return <details><summary>{t("通知渠道与投递记录")}</summary><Flex direction="column" gap="3" mt="3"><Text size="1" color="gray">{t("先配置渠道，再在定时任务中选择通知对象。私密 URL、签名密钥和 SMTP 密码不通过列表返回。通知只包含脱敏结果摘要。")}</Text>
 {targets.data?.map(channel=><Card key={channel.id}><Flex gap="3" wrap="wrap" align="center"><Text weight="medium">{channel.settings.name}</Text><Text>{channel.settings.kind} · {channel.origin||channel.smtp?.host}</Text><Text>{channel.settings.enabled?t("已启用"):t("已停用")}</Text><Button variant="soft" disabled={pending} onClick={()=>choose(channel)}>{t("编辑通知渠道")}</Button><Button variant="ghost" disabled={pending} onClick={()=>void action(`notifications/${channel.id}`,{expected_revision:channel.revision},"DELETE")}>{t("删除通知渠道")}</Button></Flex></Card>)}
 <Button variant="soft" disabled={pending} onClick={()=>setEdit(fresh())}>{t("新建通知渠道")}</Button><Flex gap="3" wrap="wrap"><Field label={t("通知对象名称")}><TextField.Root value={settings.name} disabled={pending} maxLength={256} onChange={event=>change({name:event.target.value})}/></Field><Choice label={t("通知渠道")} value={settings.kind} disabled={pending} options={[{value:"webhook",label:"Webhook"},{value:"slack",label:"Slack"},{value:"teams",label:"Teams Workflow"},{value:"wecom",label:t("企业微信")},{value:"dingtalk",label:t("钉钉")},{value:"feishu",label:t("飞书")},{value:"jenkins",label:"Jenkins"},{value:"pagerduty",label:"PagerDuty"},{value:"email",label:"SMTP Email"}]} onChange={kind=>setEdit({...fresh(),id:edit.id,revision:edit.revision,settings:{...settings,kind}})}/><Choice label={t("通知语言")} value={settings.language} disabled={pending} options={[{value:"en",label:"English"},{value:"zh-CN",label:t("简体中文")}]} onChange={language=>change({language:language as "en"|"zh-CN"})}/></Flex>
 <Flex gap="3" wrap="wrap">{["passed","failed","cancelled","interrupted"].map(status=><label key={status} className="checkbox-label"><Checkbox checked={settings.statuses.includes(status)} disabled={pending} onCheckedChange={value=>change({statuses:value===true?[...settings.statuses,status]:settings.statuses.filter(item=>item!==status)})}/>{status==="passed"?t("通过"):status==="failed"?t("失败"):status==="cancelled"?t("已取消"):t("运行已中断")}</label>)}<label className="checkbox-label"><Checkbox checked={settings.changes_only} disabled={pending} onCheckedChange={value=>change({changes_only:value===true})}/>{t("仅结果状态改变时通知")}</label><label className="checkbox-label"><Checkbox checked={settings.enabled} disabled={pending} onCheckedChange={value=>change({enabled:value===true})}/>{t("启用通知渠道")}</label></Flex>
 {edit.id&&<label className="checkbox-label"><Checkbox checked={edit.keep} disabled={pending} onCheckedChange={value=>setEdit({...edit,keep:value===true})}/>{t("保留已保存的私密凭据")}</label>}
 {settings.kind!=="email"?<Flex direction="column" gap="2"><Field label={t("私密服务 URL")}><TextField.Root type="password" value={edit.endpoint} disabled={pending||edit.keep} maxLength={8192} onChange={event=>setEdit({...edit,endpoint:event.target.value})}/></Field><Field label={t("签名密钥 / Jenkins Bearer")}><TextField.Root type="password" value={edit.signing_secret} disabled={pending||edit.keep} maxLength={4096} onChange={event=>setEdit({...edit,signing_secret:event.target.value})}/></Field>{settings.kind==="pagerduty"&&<Field label={t("PagerDuty Routing Key")}><TextField.Root type="password" value={edit.routing_key} disabled={pending||edit.keep} maxLength={4096} onChange={event=>setEdit({...edit,routing_key:event.target.value})}/></Field>}</Flex>:<Flex direction="column" gap="2"><Flex gap="3" wrap="wrap"><Field label={t("SMTP 主机")}><TextField.Root value={edit.host} disabled={pending} onChange={event=>setEdit({...edit,host:event.target.value})}/></Field><Field label={t("SMTP 端口")}><TextField.Root type="number" min={1} max={65535} value={edit.port} disabled={pending} onChange={event=>setEdit({...edit,port:Number(event.target.value)})}/></Field><Choice label={t("SMTP TLS 模式")} value={edit.tls} disabled={pending} options={[{value:"starttls",label:"STARTTLS"},{value:"tls",label:"TLS"},{value:"none",label:t("无 TLS（受信任 SMTP）")}]} onChange={tls=>setEdit({...edit,tls})}/></Flex><Field label={t("发件邮箱")}><TextField.Root value={edit.from} disabled={pending} onChange={event=>setEdit({...edit,from:event.target.value})}/></Field><Field label={t("收件邮箱（每行一个）")}><TextArea value={edit.to} disabled={pending} onChange={event=>setEdit({...edit,to:event.target.value})}/></Field><Field label={t("SMTP 用户名")}><TextField.Root value={edit.username} disabled={pending||edit.keep} onChange={event=>setEdit({...edit,username:event.target.value})}/></Field><Field label={t("SMTP 密码")}><TextField.Root type="password" value={edit.password} disabled={pending||edit.keep} onChange={event=>setEdit({...edit,password:event.target.value})}/></Field></Flex>}
 <Button disabled={pending||!settings.name.trim()||!settings.statuses.length} loading={pending} onClick={save}>{t("保存通知对象")}</Button>{(error||targets.error)&&<Callout.Root color="red"><Callout.Text role="alert">{error||liveError(targets.error)}</Callout.Text></Callout.Root>}
 <Text weight="medium">{t("最近的通知投递")}</Text>{ledger.data?.map(delivery=><Card key={delivery.id}><Flex gap="3" wrap="wrap"><Text>{delivery.event.schedule_name}</Text><Text>{deliveryStatus(delivery.status)} · {delivery.attempts}</Text>{delivery.last_http_status&&<Text>{delivery.last_http_status}</Text>}{["failed","cancelled"].includes(delivery.status)&&<Button variant="soft" disabled={pending} onClick={()=>void action(`notification-deliveries/${delivery.id}/retry`)}>{t("重试通知投递")}</Button>}</Flex>{delivery.last_error&&<Text as="p" size="1" color="red">{t("通知未被确认送达，请检查渠道凭据、目标策略或投递状态。")}</Text>}</Card>)}
 </Flex></details>;
}
