import {useEffect,useRef,useState} from "react";
import {useQuery,useQueryClient} from "@tanstack/react-query";
import {Button,Callout,Card,Checkbox,Flex,Text,TextField} from "@radix-ui/themes";
import {api} from "../../shared/api";
import {t,useLanguage} from "../../shared/i18n";
import {liveError} from "../../shared/i18n/errors";
import {Choice,Field} from "../../shared/ui";
import {useWorkbench} from "../workbench/context";
import type {ScheduledRun,ScheduleDefinition,ScheduledOccurrence,NotificationTarget} from "../../shared/types";
const status=(value:string)=>value==="passed"?t("通过"):value==="failed"?t("失败"):value==="cancelled"?t("已取消"):value==="interrupted"?t("运行已中断"):value==="running"?t("运行中"):value==="queued"?t("已排队"):value;
const fresh=(collection:string):ScheduleDefinition=>({name:"",cron:"0 9 * * *",timezone:"UTC",enabled:false,collection_id:collection,scenario_id:null,environment_id:null,dataset_id:null,iterations:null});
export default function SchedulesPanel({onReport}:{onReport:(id:string)=>void}){
 const state=useWorkbench(),{language}=useLanguage(),client=useQueryClient();const workspace=state.draft?.id??"",scope=JSON.stringify([state.accountId,workspace]);
 const [edit,setEdit]=useState<{id:string;revision:number;definition:ScheduleDefinition}>(()=>({id:"",revision:0,definition:fresh(state.draft?.data.collections[0]?.id??"")})),[pending,setPending]=useState(false),[error,setError]=useState<ReturnType<typeof liveError>>(""),[preview,setPreview]=useState<string[]>([]),[history,setHistory]=useState<{id:string;rows:ScheduledOccurrence[]}|null>(null);
 const identity=JSON.stringify([scope,edit]);const latest=useRef(identity);latest.current=identity;const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);const current=(origin:string)=>mounted.current&&latest.current===origin;
 const list=useQuery({queryKey:["schedules",state.accountId,workspace],queryFn:()=>api<ScheduledRun[]>(`/api/workspaces/${workspace}/schedules`),enabled:state.authenticated&&!!workspace,refetchInterval:5000});
 const notificationTargets=useQuery({queryKey:["notification-targets",state.accountId,workspace],queryFn:()=>api<NotificationTarget[]>(`/api/workspaces/${workspace}/notifications`),enabled:state.authenticated&&!!workspace});
 const definition=edit.definition;const change=(patch:Partial<ScheduleDefinition>)=>{setEdit({...edit,definition:{...definition,...patch}});setPreview([]);setError("");};
 async function action(path:string,body?:unknown,method="POST"){if(pending)return;const origin=identity;setPending(true);setError("");try{await api(`/api/workspaces/${workspace}/schedules${path}`,method,body);if(current(origin)){await client.invalidateQueries({queryKey:["schedules",state.accountId,workspace]});if(path===""||method==="PUT")setEdit({id:"",revision:0,definition:fresh(definition.collection_id)});}}catch(error){if(current(origin))setError(liveError(error));}finally{if(mounted.current)setPending(false);}}
 async function peek(){if(pending)return;const origin=identity;setPending(true);setError("");try{const value=await api<{next:string[]}>(`/api/workspaces/${workspace}/schedules/preview`,"POST",{cron:definition.cron,timezone:definition.timezone});if(current(origin))setPreview(value.next);}catch(error){if(current(origin))setError(liveError(error));}finally{if(mounted.current)setPending(false);}}
 async function runs(id:string){const origin=identity;setPending(true);setError("");try{const rows=await api<ScheduledOccurrence[]>(`/api/workspaces/${workspace}/schedules/${id}/runs`);if(current(origin))setHistory({id,rows});}catch(error){if(current(origin))setError(liveError(error));}finally{if(mounted.current)setPending(false);}}
 if(!state.draft)return null;const data=state.draft.data;
 return <details><summary>{t("定时任务与监控")}</summary><Flex direction="column" gap="3" mt="3"><Text size="1" color="gray">{t("启用的服务端任务退出登录后仍按计划运行；本地桌面任务需要应用保持运行。任务使用保存的环境与数据集，不复制本地变量覆盖。")}</Text>
 {list.data?.map(schedule=><Card key={schedule.id}><Flex gap="3" wrap="wrap" align="center"><Text weight="medium">{schedule.definition.name}</Text><Text>{schedule.definition.cron} · {schedule.definition.timezone}</Text><Text>{schedule.definition.enabled?t("已启用"):t("已停用")}</Text><Text>{schedule.running?t("运行中"):schedule.queued?t("已排队"):status(schedule.last_run?.status||"")}</Text></Flex>{schedule.next_run_at&&schedule.definition.enabled&&<Text as="p" size="1">{t("下次计划运行")} · {new Date(schedule.next_run_at).toLocaleString(language)}</Text>}<Flex gap="2" wrap="wrap" mt="2"><Button variant="soft" disabled={pending} onClick={()=>{setEdit({id:schedule.id,revision:schedule.revision,definition:structuredClone(schedule.definition)});setPreview([]);setError("");}}>{t("编辑任务")}</Button><Button variant="soft" disabled={pending||!!schedule.queued} onClick={()=>void action(`/${schedule.id}/run`)}>{t("立即排队运行")}</Button><Button variant="soft" disabled={pending||(!schedule.running&&!schedule.queued)} onClick={()=>void action(`/${schedule.id}/cancel`)}>{t("取消任务执行")}</Button><Button variant="soft" disabled={pending} onClick={()=>void runs(schedule.id)}>{t("任务运行记录")}</Button><Button variant="ghost" disabled={pending} onClick={()=>void action(`/${schedule.id}`,{expected_revision:schedule.revision},"DELETE")}>{t("删除任务")}</Button>{schedule.last_run?.report_id&&<Button variant="soft" onClick={()=>onReport(schedule.last_run!.report_id!)}>{t("查看任务报告")}</Button>}</Flex></Card>)}
 <Button variant="soft" disabled={pending} onClick={()=>{setEdit({id:"",revision:0,definition:fresh(data.collections[0]?.id??"")});setPreview([]);}}>{t("新建定时任务")}</Button>
 <Text size="1" color="gray">{t("时区规则使用 IANA 数据。夏令时缺失的固定执行时间顺延到首个有效时刻；保存前可预览后续时间。")}</Text>
 <Flex gap="3" wrap="wrap"><Field label={t("任务名称")}><TextField.Root value={definition.name} disabled={pending} maxLength={256} onChange={event=>change({name:event.target.value})}/></Field><Field label={t("Cron 表达式（秒可选）")}><TextField.Root value={definition.cron} disabled={pending} maxLength={256} onChange={event=>change({cron:event.target.value})}/></Field><Field label={t("IANA 时区")}><TextField.Root value={definition.timezone} disabled={pending} maxLength={128} onChange={event=>change({timezone:event.target.value})}/></Field><Button variant="soft" disabled={pending} onClick={()=>void peek()}>{t("预览后续执行时间")}</Button></Flex>
 <Flex gap="3" wrap="wrap"><Choice label={t("任务集合")} value={definition.collection_id||"none"} options={data.collections.map(collection=>({value:collection.id,label:collection.name}))} disabled={pending} onChange={collection_id=>change({collection_id,scenario_id:null})}/><Choice label={t("任务场景")} value={definition.scenario_id??"none"} options={[{value:"none",label:t("集合原始顺序")},...(data.scenarios??[]).filter(scenario=>scenario.collection_id===definition.collection_id).map(scenario=>({value:scenario.id,label:scenario.name}))]} disabled={pending} onChange={value=>change({scenario_id:value==="none"?null:value})}/><Choice label={t("任务环境")} value={definition.environment_id??"none"} options={[{value:"none",label:t("使用工作区当前环境")},...data.environments.map(environment=>({value:environment.id,label:environment.name}))]} disabled={pending} onChange={value=>change({environment_id:value==="none"?null:value})}/><Choice label={t("任务数据集")} value={definition.dataset_id??"none"} options={[{value:"none",label:t("不选择数据集")},...(data.datasets??[]).filter(dataset=>dataset.source).map(dataset=>({value:dataset.id,label:dataset.name}))]} disabled={pending} onChange={value=>change({dataset_id:value==="none"?null:value})}/><Field label={t("任务迭代次数（空值使用数据行数）")}><TextField.Root type="number" min={1} max={100} value={definition.iterations??""} disabled={pending} onChange={event=>change({iterations:event.target.value?Number(event.target.value):null})}/></Field></Flex>
 <Flex gap="3" wrap="wrap">{notificationTargets.data?.map(channel=><label key={channel.id} className="checkbox-label"><Checkbox disabled={pending} checked={(definition.notification_ids??[]).includes(channel.id)} onCheckedChange={value=>change({notification_ids:value===true?[...(definition.notification_ids??[]),channel.id]:(definition.notification_ids??[]).filter(id=>id!==channel.id)})}/>{t("通知对象")} · {channel.settings.name}</label>)}</Flex>
 <label className="checkbox-label"><Checkbox checked={definition.enabled} disabled={pending} onCheckedChange={value=>change({enabled:value===true})}/>{t("启用计划运行")}</label><Button loading={pending} disabled={pending||!definition.name.trim()||!definition.collection_id} onClick={()=>void action(edit.id?`/${edit.id}`:"",edit.id?{definition,expected_revision:edit.revision}:definition,edit.id?"PUT":"POST")}>{t("保存定时任务")}</Button>
 {preview.map(value=><Text key={value} size="1">{new Date(value).toLocaleString(language)}</Text>)}{(error||list.error)&&<Callout.Root color="red"><Callout.Text role="alert">{error||liveError(list.error)}</Callout.Text></Callout.Root>}
 {history&&<><Text weight="medium">{t("任务运行记录")}</Text>{history.rows.map(run=><Card key={run.id}><Text>{status(run.status)} · {new Date(run.started_at).toLocaleString(language)} · {run.passed} / {run.failed} / {run.skipped}</Text>{run.error&&<Text as="p" size="1" color="red">{t("任务运行异常，请检查配置、运行容量或中断状态。")}</Text>}{run.report_id&&<Button variant="soft" onClick={()=>onReport(run.report_id!)}>{t("查看任务报告")}</Button>}</Card>)}</>}
 </Flex></details>;
}
