// One-time migration. Babel identifies literals; range edits preserve surrounding source.
const fs=require('fs'),path=require('path');const parser=require('../../web/node_modules/@babel/parser');const traverse=require('../../web/node_modules/@babel/traverse').default;
const catalog=JSON.parse(fs.readFileSync('web/src/shared/i18n/zh-CN.json','utf8'));
function scan(dir){for(const name of fs.readdirSync(dir)){const file=path.join(dir,name);if(fs.statSync(file).isDirectory()){if(name!=='i18n')scan(file);continue;}if(!/\.tsx?$/.test(name)||/\.test\./.test(name))continue;const source=fs.readFileSync(file,'utf8');if (/import.*from.*i18n/.test(source)) continue;const ast=parser.parse(source,{sourceType:'module',plugins:['typescript','jsx']});const edits=[];let translated=false,subscribed=false;
const translate=(key,values)=>`t(${JSON.stringify(key)}${values?', { '+values+' }':''})`;
traverse(ast,{
Function(p){const n=p.node;const label=n.id?.name||(p.parent.type==='VariableDeclarator'?p.parent.id.name:'');if((/^[A-Z]/.test(label)||/^use[A-Z]/.test(label))&&n.body.type==='BlockStatement'){let jsx=false;p.traverse({JSXElement(){jsx=true}});if(jsx||/^use[A-Z]/.test(label)){edits.push({start:n.body.start+1,end:n.body.start+1,text:'\n  useLanguage();'});subscribed=true;}}},
StringLiteral(p){const key=p.node.value;if(!Object.hasOwn(catalog,key))return;if(p.parent.type==='ObjectProperty'&&p.key==='key')return;const call=translate(key);if(!p.getFunctionParent()&&p.parent.type==='ObjectProperty'&&p.key==='value'){const prop=p.parent;const property=source.slice(prop.key.start,prop.key.end);edits.push({start:prop.start,end:prop.end,text:`get ${property}() { return ${call}; }`});}else{edits.push({start:p.node.start,end:p.node.end,text:p.parent.type==='JSXAttribute'?`{${call}}`:call});}translated=true;},
JSXText(p){const key=p.node.value.replace(/\s+/g,' ').trim();if(!Object.hasOwn(catalog,key))return;const leading=/^\s/.test(p.node.value)?' ':'';const trailing=/\s$/.test(p.node.value)?' ':'';edits.push({start:p.node.start,end:p.node.end,text:`${leading}{${translate(key)}}${trailing}`});translated=true;},
TemplateLiteral(p){const key=p.node.quasis.map((q,i)=>q.value.cooked+(i<p.node.expressions.length?`{{value${i}}}`:'')).join('');if(!Object.hasOwn(catalog,key))return;const values=p.node.expressions.map((expr,i)=>`value${i}: ${source.slice(expr.start,expr.end)}`).join(', ');edits.push({start:p.node.start,end:p.node.end,text:translate(key,values)});translated=true;p.skip();}
});if(!edits.length)continue;const relative=path.relative(path.dirname(file),'web/src/shared/i18n').replaceAll(path.sep,'/');const imports=[translated?'t':null,subscribed?'useLanguage':null].filter(Boolean).join(', ');let out=source;for(const e of edits.sort((a,b)=>b.start-a.start))out=out.slice(0,e.start)+e.text+out.slice(e.end);fs.writeFileSync(file,`import { ${imports} } from "${relative.startsWith('.')?relative:'./'+relative}";\n`+out);}}
scan('web/src');
