import {useEffect,useRef,useState} from "react";
import {useQuery,useQueryClient} from "@tanstack/react-query";
import {Badge,Button,Callout,Card,Dialog,Flex,Table,Text} from "@radix-ui/themes";
import {api} from "../../shared/api";
import {t,useLanguage,message} from "../../shared/i18n";
import {liveError} from "../../shared/i18n/errors";
import {Choice} from "../../shared/ui";
import {useWorkbench} from "../workbench/context";
import ReportResponse from "./ReportResponse";
import {saveProjectFile} from "../generation/saveProjectFile";
import type {ExportResult,RunReportPage,SavedRunReport} from "../../shared/types";
export default function SavedReports({disabled}:{disabled:boolean}){
 const state=useWorkbench(),{language}=useLanguage(),client=useQueryClient();
 const [responsePosition,setResponsePosition]=useState<number|null>(null);
 const workspaceId=state.draft?.id??"",accountId=state.accountId,scope=JSON.stringify([accountId,workspaceId]);
 const [cursor,setCursor]=useState(""),[selected,setSelected]=useState(""),[format,setFormat]=useState("html"),[filter,setFilter]=useState("all"),[page,setPage]=useState(0),[pending,setPending]=useState(false),[error,setError]=useState<ReturnType<typeof liveError>>("");
 const identity=JSON.stringify([scope,selected,language]);const latest=useRef(identity);latest.current=identity;const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const list=useQuery({queryKey:["run-reports",accountId,workspaceId,cursor],queryFn:()=>api<RunReportPage>(`/api/workspaces/${workspaceId}/reports?limit=20${cursor?`&cursor=${encodeURIComponent(cursor)}`:""}`),enabled:!!workspaceId&&state.authenticated});
 const detail=useQuery({queryKey:["run-report",accountId,workspaceId,selected],queryFn:()=>api<SavedRunReport>(`/api/workspaces/${workspaceId}/reports/${selected}`),enabled:!!selected&&!!workspaceId&&state.authenticated});
 const current=(origin=identity)=>mounted.current&&latest.current===origin;
 async function remove(reportId?:string){if(!current())return;const origin=identity;setPending(true);setError("");try{await api(`/api/workspaces/${workspaceId}/reports${reportId?`/${reportId}`:""}`,"DELETE");if(!current(origin))return;setSelected("");setCursor("");await client.invalidateQueries({queryKey:["run-reports",accountId,workspaceId]});}catch(error){if(current(origin))setError(liveError(error));}finally{if(mounted.current)setPending(false);}}
 function clear(){state.setGuard({title:message("清空保存的测试报告"),description:message("删除此工作区保存的报告，不影响接口、变量或请求历史。"),action:()=>remove()});}
 async function download(){if(!selected||pending)return;const origin=identity;setPending(true);setError("");try{const file=await api<ExportResult>(`/api/workspaces/${workspaceId}/reports/${selected}/export?format=${format}&language=${language}`);if(!current(origin))return;await saveProjectFile(file.filename,new TextEncoder().encode(file.content),()=>current(origin));}catch(error){if(current(origin))setError(liveError(error));}finally{if(mounted.current)setPending(false);}}
 if(!state.draft)return null;
 const report=detail.data;const rows=(report?.results??[]).filter(row=>filter==="all"||row.outcome===filter);const shown=rows.slice(page*20,(page+1)*20);
 return <details><summary>{t("保存的测试报告")}</summary><Flex direction="column" gap="3" mt="3">
 <Text size="1" color="gray">{t("运行后自动保存脱敏报告，每个工作区保留最近 100 份。报告不包含即时正文、响应头、日志或变量值。")}</Text>
 <Flex gap="2" wrap="wrap"><Button variant="soft" disabled={disabled||pending||list.isFetching} onClick={()=>{setCursor("");void list.refetch();}}>{t("刷新报告")}</Button><Button variant="ghost" disabled={disabled||pending||!list.data?.items.length} onClick={clear}>{t("清空报告")}</Button>{cursor&&<Button variant="soft" disabled={pending} onClick={()=>setCursor("")}>{t("最新报告")}</Button>}{list.data?.next_cursor&&<Button variant="soft" disabled={pending||list.isFetching} onClick={()=>setCursor(list.data!.next_cursor!)}>{t("更早的报告")}</Button>}</Flex>
 {(error||list.error)&&<Callout.Root color="red"><Callout.Text role="alert">{error||liveError(list.error)}</Callout.Text></Callout.Root>}
 <Table.Root><Table.Header><Table.Row><Table.ColumnHeaderCell>{t("集合 / 场景")}</Table.ColumnHeaderCell><Table.ColumnHeaderCell>{t("通过 / 失败 / 跳过")}</Table.ColumnHeaderCell><Table.ColumnHeaderCell>{t("完成时间")}</Table.ColumnHeaderCell><Table.ColumnHeaderCell>{t("报告操作")}</Table.ColumnHeaderCell></Table.Row></Table.Header><Table.Body>{list.data?.items.map(item=><Table.Row key={item.id}><Table.Cell>{item.scenario_name||item.collection_name}{item.summary.stopped_reason&&<Text as="p" size="1" color="red">{t("流程未正常完成")}</Text>}</Table.Cell><Table.Cell>{item.summary.passed} / {item.summary.failed} / {item.summary.skipped}</Table.Cell><Table.Cell>{new Date(item.finished_at).toLocaleString(language)}</Table.Cell><Table.Cell><Flex gap="2"><Button variant="soft" disabled={pending} onClick={()=>{setSelected(item.id);setResponsePosition(null);setPage(0);setFilter("all");setError("");}}>{t("查看报告")}</Button><Button variant="ghost" disabled={disabled||pending} onClick={()=>void remove(item.id)}>{t("删除报告")}</Button></Flex></Table.Cell></Table.Row>)}</Table.Body></Table.Root>
 {list.data?.items.length===0&&<Text color="gray">{t("暂无保存的报告，运行集合或场景后会自动生成。")}</Text>}
 <Dialog.Root open={!!selected} onOpenChange={open=>{if(!open){setSelected("");setResponsePosition(null);}}}><Dialog.Content maxWidth="min(1040px, calc(100vw - 32px))"><Dialog.Title>{t("测试报告详情")}</Dialog.Title><Dialog.Description>{t("按运行时工作区版本记录步骤、断言与耗时。省略的诊断会单独计数。")}</Dialog.Description>
 {detail.isFetching&&!report&&<Text role="status">{t("正在读取报告…")}</Text>}{detail.error&&<Callout.Root color="red"><Callout.Text role="alert">{liveError(detail.error)}</Callout.Text></Callout.Root>}
 {report&&<><Flex gap="3" wrap="wrap" my="3"><Text>{report.scenario_name||report.collection_name}</Text><Text>{t("来源工作区版本")} {report.workspace_revision}</Text><Badge color="green">{t("通过")} {report.summary.passed}</Badge><Badge color="red">{t("失败")} {report.summary.failed}</Badge><Badge color="gray">{t("跳过")} {report.summary.skipped}</Badge><Text>{report.summary.elapsed_ms} ms</Text></Flex>{report.summary.stopped_reason&&<Callout.Root color="orange"><Callout.Text>{t("流程未正常完成")} · {report.summary.stopped_reason}</Callout.Text></Callout.Root>}
 <Flex gap="3" align="center" wrap="wrap" my="3"><Choice label={t("报告导出格式")} value={format} disabled={pending} onChange={setFormat} options={[{value:"html",label:"HTML"},{value:"json",label:"JSON"},{value:"csv",label:"CSV"},{value:"junit",label:"JUnit XML"}]}/><Button disabled={pending} loading={pending} onClick={()=>void download()}>{t("下载脱敏报告")}</Button><Choice label={t("报告步骤筛选")} value={filter} onChange={value=>{setFilter(value);setPage(0);}} options={[{value:"all",label:t("全部步骤")},{value:"failed",label:t("失败步骤")},{value:"skipped",label:t("跳过步骤")},{value:"passed",label:t("通过步骤")} ]}/></Flex>
 {shown.map(row=><Card key={row.position} my="2"><Flex gap="3" justify="between" wrap="wrap"><Text weight="medium">{row.position+1} · {row.step_name||row.request_name}</Text><Badge color={row.outcome==="failed"?"red":row.outcome==="passed"?"green":"gray"}>{row.outcome==="failed"?t("失败"):row.outcome==="passed"?t("通过"):t("跳过")}{row.status!==null?` / ${row.status}`:""}</Badge><Text>{row.elapsed_ms} ms</Text></Flex><Text size="1" color="gray">{t("第 {{iteration}} 轮",{iteration:row.iteration+1})} · {row.method} · {row.parallel_name||row.step_group}</Text>{row.error&&<Text as="p" color="red">{t("请求执行失败，详细诊断仅在即时结果中显示。")}</Text>}{!!row.diagnostics_omitted&&<Text as="p" size="1">{t("省略的断言详情：{{count}}",{count:row.diagnostics_omitted})}</Text>}
 {row.tests.length>0&&<details><summary>{t("断言详情")} ({row.tests_failed} / {row.tests_passed+row.tests_failed})</summary>{row.tests.map((test,index)=><Text as="p" size="2" key={`${test.id}:${index}`} color={test.passed?"green":"red"}>{test.name} · {test.actual} · {test.expected}</Text>)}</details>}
 {row.history_id&&<Button variant="soft" onClick={()=>setResponsePosition(row.position)}>{t("查看脱敏历史响应")}</Button>}
 {row.outcome==="failed"&&state.draft?.data.collections.some(collection=>collection.requests.some(request=>request.id===row.request_id))&&<Button variant="ghost" onClick={()=>{state.setRequestId(row.request_id);state.setView("requests");setSelected("");}}>{t("打开当前接口")}</Button>}
 </Card>)}<Flex gap="3" justify="between" my="3"><Button variant="soft" disabled={page===0} onClick={()=>setPage(page-1)}>{t("上一页步骤")}</Button><Text>{page+1} / {Math.max(1,Math.ceil(rows.length/20))}</Text><Button variant="soft" disabled={(page+1)*20>=rows.length} onClick={()=>setPage(page+1)}>{t("下一页步骤")}</Button></Flex></>}
 {report&&responsePosition!==null&&<ReportResponse key={JSON.stringify([scope,selected,responsePosition])} accountId={accountId} workspaceId={workspaceId} reportId={selected} position={responsePosition} dark={state.dark} onClose={()=>setResponsePosition(null)}/>}
 {error&&<Text role="alert" color="red">{error}</Text>}<Flex justify="end"><Dialog.Close><Button variant="soft">{t("关闭")}</Button></Dialog.Close></Flex>
 </Dialog.Content></Dialog.Root>
 </Flex></details>;
}
