[package]
name = "moleapi-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
apollo-parser.workspace = true
cynic-parser.workspace = true
async-graphql-parser.workspace = true
cynic.workspace = true
cynic-introspection.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
reqwest.workspace = true
uuid.workspace = true
url = "2"
base64 = "0.22"
futures-util = "0.3"

[dev-dependencies]
axum.workspace = true
