[package]
name = "moleapi-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
aws-sigv4 = { version="=1.4.5", default-features=false, features=["sign-http", "http1"] }
aws-credential-types = "=1.2.14"
http = "1"
oauth2 = {version="=5.0.0",default-features=false}
jsonwebtoken = { version="=11.1.0", default-features=false, features=["rust_crypto","use_pem"] }
digest_auth = "=0.3.1"
pem = "=4.0.0"
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
hex = "0.4"
prost.workspace = true
prost-reflect.workspace = true
protox.workspace = true
apollo-parser.workspace = true
cynic-parser.workspace = true
async-graphql-parser.workspace = true
cynic.workspace = true
cynic-introspection.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
reqwest.workspace = true
uuid.workspace = true
url = "2"
base64 = "0.22"
futures-util = "0.3"

rumqttc = { version = "=0.25.1", default-features = false, features = ["use-rustls-no-provider", "websocket"] }

mime = "0.3"
wsdl = "=0.1.3"
roxmltree = "0.18"
xmltree = "=0.11.0"
quick-xml = "0.38"
xsd-parser = "=1.5.2"

[dev-dependencies]
sha2 = "0.10"
prost-types = "0.14"
axum = { workspace = true, features = ["multipart"] }
